#!/usr/bin/perl
# Place in /usr/local/bin/ or similar path that is in $PATH
# use like so:
# $ cat something.txt | uppercase
# $ uppercase thistexthere
use strict;
use warnings;
if ( $ARGV[0] ) {
	foreach my $arg (@ARGV) {
		print uc($arg) . "\n";
	}
} else {
	while (<STDIN>) {
		print uc($_);
	}
}
